### PR TITLE
Entry/mike

### PR DESCRIPTION
**Pull request by mambrocio**
Created my branch.

Stylized form and added appropriate divs and layout. Made Stylized two sections so far. Will work on result side of the page later on. Not responsive yet. 

Please pull from branch to see difference.

### CODE REVIEW

**Comment by JoshuaVaneps** [comment]
changes to the form

**Review by JoshuaVaneps — COMMENTED** [review]
changing form

**Comment by mambrocio** [comment]
Added result section. Added new font color. Might change color scheme, for body background.

**Review by JoshuaVaneps — APPROVED** [review]
adding a result section

**Pull request merged**
